<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2c2f5a2f1f6fbee49e910a187951af83
{
    public static $prefixLengthsPsr4 = array (
        'g' => 
        array (
            'getgigwp\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'getgigwp\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2c2f5a2f1f6fbee49e910a187951af83::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2c2f5a2f1f6fbee49e910a187951af83::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2c2f5a2f1f6fbee49e910a187951af83::$classMap;

        }, null, ClassLoader::class);
    }
}
